services:
    app:
      build: .
      container_name: spring_dev
      ports:
        - "3030:3030"
      depends_on:
        - mongo

    mongo:
      image: mongo:5.0.31
      container_name: mongo_db
      ports:
        - "27017:27017"
      volumes:
        - mongo-data:/data/db

volumes:
  mongo-data: